#!/usr/bin/env bash


export __LOG__="$__CACHE__/$__APP__.log"


__logging_debug () {
  [[ "$__DEBUG__" == 0 ]] && {
    >&2 printf "[DEBUG]   %s  %s\n" \
      "$(date +"%m-%d-%Y")  $(date +"%T")" "$*" \
      >> "$__LOG__"
  }

  return 0
}


__logging_info () {
  >&2 printf "[INFO]    %s  %s\n" \
    "$(date +"%m-%d-%Y")  $(date +"%T")" "$*" \
    >> "$__LOG__"

  return 0
}


__logging_warning () {
  >&2 printf "[WARNING] %s  %s\n" \
    "$(date +"%m-%d-%Y")  $(date +"%T")" "$*" \
    >> "$__LOG__"

  return 0
}


__logging_error () {
  >&2 printf "[ERROR]   %s  %s\n" \
    "$(date +"%m-%d-%Y")  $(date +"%T")" "$*" \
    >> "$__LOG__"

  return 0
}


__logging_fatal () {
  >&2 printf "[FATAL]   %s  %s\n" \
    "$(date +"%m-%d-%Y")  $(date +"%T")" "$*" \
    | tee -a "$__LOG__"

  exit 1
}
